# Generated by Django 3.1.4 on 2020-12-01 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('okpd2', models.CharField(max_length=100)),
                ('okei', models.CharField(max_length=3)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.calculation')),
                ('composition_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.compositionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('ACCEPTED', 'Принят в работу Исполнителем'), ('FORMED_CALCULATION', 'Сформирован расчет'), ('RETURNED', 'Возвращен исполнителю'), ('CONTRACTOR_REMOVED', 'Исполнитель с расчета снят'), ('EXPIRED', 'Просрочен')], default='CREATED', max_length=100)),
                ('resolution', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.request')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='compositionrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.request'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.request'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
